import { MapObjectName } from '../map'

type OBJ_INFO = {
  id: number
  name: string
}

// NEW_ASSET: uncomment corresponding line & adapt
export const BMAP_OBJ_INFO: Record<MapObjectName, OBJ_INFO> = {
  // '1x2_desert_block.png': 0,
  block: { id: 0, name: 'Block (1x1)' },
  ramp_bottom_right: { id: 1, name: 'Ramp A' }, // ramp A
  ramp_bottom_left: { id: 2, name: 'Ramp B' }, // ramp B
  ramp_top_right: { id: 3, name: 'Ramp C' }, // ramp C
  ramp_top_left: { id: 4, name: 'Ramp D' }, // ramp D
  terrain: { id: 5, name: 'Terrain' },
  // 'Polygon Tool': 6,
  spawn_player: { id: 7, name: 'Player Spawn' },
  // 'USC Spawn': 8,
  // 'THE MAN Spawn': 9,
  // 'USC CTF Flag': 10,
  // 'THE MAN CTF Flag': 11,
  // 'TDM Flag': 12,
  // Waypoint: 13,
  // 'Waypoint Block': 14,
  // Patrolpoint: 15,
  ladder: { id: 16, name: 'Ladder (Metal)' },
  // 'Window (Vertical)': 17,
  // 'Explosive Barrel': 18,
  // 'Floor Spikes': 19,
  // 'Spike Trap (Trigger)': 20,
  // 'Medikit Spawn': 21,
  // 'Ammobox Spawn': 22,
  // 'USC Generator': 23,
  // 'USC Turret': 24,
  // 'USC Resupply': 25,
  // 'THE MAN Generator': 26,
  // 'THE MAN Turret': 27,
  // 'THE MAN Resupply': 28,
  // 'Swinging Axe': 29,
  // 'Ladder (Wood)': 30,
  // Water: 31,
  // Lava: 32,
  // 'Empty Sea': 33,
  // 'Moving Platform': 35,
  // 'Climb Flag': 36,
  // 'Platform Tool': 37,
  // 'Triple Damage': 38,
  // 'Super Speed': 39,
  // Invisibility: 40,
  // Regeneration: 41,
  // 'Block (4x1)': 42,
  // 'Block (1x4)': 43,
  // 'Chest Spawn (Survival)': 44,
  // 'Objective Spawn (Survival)': 45,
  // 'Wall Tool': 46,
  // Button: 47,
  // Lever: 48,
  // 'Door (Manual, vertical)': 49,
  // Key: 50,
  // 'AND Logic Gate': 51,
  // 'OR Logic Gate': 52,
  // 'NOT Logic Gate': 53,
  // 'ON Logic Gate': 54,
  // 'Logic Line': 55,
  // 'Pressure Plate': 56,
  // 'Door (Manual, horizontal)': 57,
  // 'Laser Trap': 58,
  // 'Conveyor Belt (Right)': 59,
  // 'Conveyor Belt (Left)': 60,
  // 'TIMER Logic Gate': 61,
  // 'Weapon Cabinet': 62,
  // 'Block (2x2)': 63,
  // 'Bar Spawn (Survival)': 64,
  // Shark: 65,
  // Teleporter: 66,
  // 'USC Teleporter': 67,
  // 'THE MAN Teleporter': 68,
  // 'Weapon Printer': 69,
  // 'Window (Horizontal)': 70,
  // 'Trigger Area': 71,
  // 'Door (Auto, vertical)': 72,
  // 'Door (Auto, horizontal)': 73,
  // 'Spike Trap (Manual)': 74,
  // 'RESET Logic Gate': 75,
  // 'COUNT Logic Gate': 76,
  // '4EVER Logic Gate': 77,
  // 'Number Display': 78,
  // 'Wood Target': 79,
  // 'Weapon Printer (Zombrains)': 80,
  // 'GAMEMODE Logic Gate': 81,
  // 'COMMAND Logic Gate': 82,
  // 'Helicopter Spawn (Zombrains)': 83,
  // 'Ladder Tool (Metal)': 84,
  // 'Ladder Tool (Wood)': 85,
  // 'STOPWATCH Logic Gate': 86,
  // 'Takeover Flag': 87,
  long_ramp_bottom_right: { id: 88, name: 'Long Ramp A' }, // 'Long Ramp A': 88,
  long_ramp_bottom_left: { id: 89, name: 'Long Ramp B' }, // 'Long Ramp B': 89,
  long_ramp_top_right: { id: 90, name: 'Long Ramp C' }, // 'Long Ramp C': 90,
  long_ramp_top_left: { id: 91, name: 'Long Ramp D' }, // 'Long Ramp D': 91,
  // 'Waypoint Divert': 92,
  // 'Waypoint Crouch': 93,
  // 'Zombie Spawn (Zombrains)': 94,
  // 'Enemy Spawn (Survival)': 95,
  // 'ENEMY Logic Gate': 96,
  // 'Weapon Spawn': 97,
  // 'PLAYER Logic Gate': 98,
  // Enemy: 99,
  // 'CALCULATE Logic Gate': 100,
  // 'RANDOM Logic Gate': 101,
  // 'Keybind Event (Host only)': 102,
  // 'Beacon Spawn (Survival)': 103,
  // 'Conveyor Belt Tool (Right)': 104,
  // 'Conveyor Belt Tool (Left)': 105,
  // 'Background Changer': 106,
  // BFG: 107,
  // 'strip10_cashonly.png': 255,
}
